{
  "format_version": 2,
  "sksl": {
    "entrypoint": "frenzy_aurora_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float uTime;\nuniform float uIntensity;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / max(uResolution, vec2(1.0));\n    vec2 centered = uv - vec2(0.5);\n    float dist = length(centered);\n    float angle = atan(centered.y, centered.x);\n    float sunRays = (sin((angle * 12.0) + (uTime * 2.2000000476837158203125)) * 0.5) + 0.5;\n    sunRays = pow(sunRays, 3.0);\n    float ringPhase = fract((uTime * 0.800000011920928955078125) - (dist * 2.0));\n    float ring = smoothstep(0.0, 0.1500000059604644775390625, ringPhase) * smoothstep(0.4000000059604644775390625, 0.1500000059604644775390625, ringPhase);\n    vec3 deepAmber = vec3(0.85000002384185791015625, 0.37999999523162841796875, 0.0500000007450580596923828125);\n    vec3 brightGold = vec3(1.0, 0.819999992847442626953125, 0.119999997317790985107421875);\n    vec3 whiteSolar = vec3(1.0, 0.980000019073486328125, 0.699999988079071044921875);\n    vec3 col = mix(deepAmber, brightGold, vec3((sunRays * 0.699999988079071044921875) + (ring * 0.300000011920928955078125)));\n    col = mix(col, whiteSolar, vec3(max(0.0, 1.0 - (dist * 2.2000000476837158203125))));\n    float pulse = 0.89999997615814208984375 + (0.25 * sin(uTime * 4.0));\n    col *= (pulse * uIntensity);\n    float alpha = clamp(((1.0 - (dist * 1.5)) * 0.819999992847442626953125) * uIntensity, 0.0, 0.819999992847442626953125);\n    fragColor = vec4(col * alpha, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uIntensity",
        "rows": 1,
        "type": 10
      }
    ]
  }
}