{
  "format_version": 2,
  "sksl": {
    "entrypoint": "post_process_diorama_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float uTime;\nuniform float uDioramaStrength;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / max(uResolution, vec2(1.0));\n    vec2 centered = uv - vec2(0.5);\n    float focusBand = abs(centered.y);\n    float dofBlur = smoothstep(0.180000007152557373046875, 0.4799999892711639404296875, focusBand) * uDioramaStrength;\n    float vignette = 1.0 - dot(centered * 1.14999997615814208984375, centered * 1.14999997615814208984375);\n    vignette = clamp(pow(vignette, 1.39999997615814208984375), 0.0, 1.0);\n    vec3 warmTint = vec3(0.980000019073486328125, 0.949999988079071044921875, 0.87999999523162841796875);\n    vec3 shadowColor = vec3(0.039999999105930328369140625, 0.0599999986588954925537109375, 0.119999997317790985107421875);\n    float horizonGlow = (smoothstep(0.4000000059604644775390625, 0.0, uv.y) * 0.119999997317790985107421875) * uDioramaStrength;\n    vec3 col = mix(shadowColor, warmTint, vec3(vignette));\n    col += (vec3(0.85000002384185791015625, 0.920000016689300537109375, 1.0) * horizonGlow);\n    float alpha = clamp((((1.0 - vignette) * 0.449999988079071044921875) + (dofBlur * 0.3499999940395355224609375)) + horizonGlow, 0.0, 0.64999997615814208984375);\n    fragColor = vec4(col * alpha, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uDioramaStrength",
        "rows": 1,
        "type": 10
      }
    ]
  }
}