{
  "format_version": 2,
  "sksl": {
    "entrypoint": "shockwave_distortion_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float uTime;\nuniform vec2 uCenter;\nuniform float uProgress;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 coord = FLT_flutter_local_FlutterFragCoord();\n    vec2 st = (coord - uCenter) / vec2(max(uResolution.x, uResolution.y));\n    float dist = length(st * 2.2000000476837158203125);\n    float waveRadius = uProgress * 1.60000002384185791015625;\n    float waveWidth = 0.1500000059604644775390625 * (1.0 - (uProgress * 0.5));\n    float diff = abs(dist - waveRadius);\n    float ring = smoothstep(waveWidth, 0.0, diff);\n    vec3 runeGold = vec3(1.0, 0.85000002384185791015625, 0.300000011920928955078125);\n    vec3 runeCyan = vec3(0.2199999988079071044921875, 0.7400000095367431640625, 0.9700000286102294921875);\n    vec3 col = mix(runeGold, runeCyan, vec3((sin((dist * 18.0) - (uTime * 4.0)) * 0.5) + 0.5));\n    float alpha = (ring * (1.0 - uProgress)) * 0.75;\n    fragColor = vec4(col * alpha, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uCenter",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uProgress",
        "rows": 1,
        "type": 10
      }
    ]
  }
}